Improve flexibility
- Remove stagit-hook-hook and stagit-hook-install scripts

  Now users are expected to choose how to use the hook themselves.
  This is because you may want to use other hooks in addition to
  stagit-hook which wouldn't be supported by the install command.

- Remove install and reindex commands

  Now that hooks don't have to be installed, these commands can
  also be removed. The new usage is reflected in the manual.

- Allow greater control over which repositories are indexed using
  the new hasfile and repodir options

- Example of how to easily setup hooks for all git repositories
  shown in the manual

diff --git a/stagit-hook b/stagit-hook
--- a/stagit-hook
+++ b/stagit-hook
@@ -1,22 +1,21 @@
 #!/bin/sh
 
+set -e
+
 err() {
 	echo "$@" 1>&2
 	exit 1
 }
 
-# Lists repositories we want in the index, sorted by most recent
-# commit. While it's not the best way, any repository with the
-# post-update hook is listed. (So long as you haven't changed the
-# hooks directory.)
+# This should be more flexible, but it works for now.
 hooked() (
-	find "$HOME" -maxdepth 3 -path '*/hooks/post-update' | sed s./hooks/post-update$.. |
+	cd "$repodir"
+	ls -d */"$hasfile" | awk -F/ '{print $1}' |
 		while read dir
-	do (
-		cd "$dir"
-		git show -s --format="%ct	$dir" ||
+	do
+		git --git-dir "$dir" show -s --format="%ct	$dir" ||
 			err "$dir: Unable to get repo information"
-	) done | sort -rn | cut -f2-
+	done | sort -rn | cut -f2-
 )
 
 index() (
@@ -42,6 +41,8 @@ loadconfig() {
 			case $key in
 			(basedir) basedir="$val" ;;
 			(baseurl) baseurl="$val" ;;
+			(repodir) repodir="$val" ;;
+			(hasfile) hasfile="$val" ;;
 			(*) err 'Invalid configuration'
 			esac
 		done < "$rc"
@@ -52,39 +53,28 @@ rc=/etc/stagit-hook
 host="$(hostname)"
 basedir=/var/www/htdocs/"$host"/projects/
 baseurl=https://"$host"/projects/
+repodir="$HOME"
+hasfile=refs
 
 loadconfig
 
-if test $# -gt 0
-then
-	case "$1" in
-	(install)
-		shift
-		stagit-hook-install "$@"
-		"$0" reindex "$@"
-		exit ;;
-	(reindex)
-		shift
-		for d in "$@"
-		do
-			repo "$d"
-		done
-		index
-		exit ;;
-	(*)
-		err 'usage: stagit-hook [repo ...]'
-	esac
-fi
-
-printenv GIT_DIR >/dev/null ||
-	err 'error: Expected to be run as a git hook'
-
 err="$(mktemp -t stagit-hook-errXXXXXX)"
 trap 'rm -f "$err"' EXIT
-{
-	repo "$GIT_DIR"
+	# Can't use "${@:-"$GIT_DIR"}" because empty GIT_DIR runs
+	# with empty string instead of just indexing like it should
+	test $# -eq 0 -a -n "$GIT_DIR" &&
+		set -- "$GIT_DIR"
+	for d in "$@"
+	do
+		repo "$d" || {
+			status=$?
+			echo "$d: Unable to generate" 1>&2
+		}
+	done
 	index
+{
+	exit $status
 } > "$err" 2>&1 || {
-	logger -t stagit-hook -p error < "$err"
+	logger -st stagit-hook -p error < "$err"
 	exit 1
 }
